apiVersion: batch/v1
kind: Job
metadata:
    name: {{ include "cm.fullname" . }}-db-init
    labels:
        app.kubernetes.io/name: {{ include "cm.name" . }}
        helm.sh/chart: {{ include "cm.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    annotations:
        "helm.sh/hook": "pre-install"
        "helm.sh/hook-weight": "30"
        "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
    template:
        metadata:
            labels:
                app.kubernetes.io/name: {{ include "cm.name" . }}
                app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
            restartPolicy: OnFailure
            initContainers:
                - name: {{ .Chart.Name }}-init-wait-for-db
                  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  command:
                      - sh
                      - "-c"
                      - |
                          until `nc -w 2 -z {{ .Values.global.dbHost }} {{ .Values.global.dbPort }} 2>&1`; do
                              echo `/bin/date "+%Y-%m-%dT%H:%M:%S%z "` [cm-db-init] waiting for db | nc {{ .Values.global.ncHost }} {{ .Values.global.ncPort }};
                              sleep 2;
                          done
                          echo `/bin/date "+%Y-%m-%dT%H:%M:%S%z "` [cm-db-init] `nc -z -v {{ .Values.global.dbHost }} {{ .Values.global.dbPort }} 2>&1` | nc {{ .Values.global.ncHost }} {{ .Values.global.ncPort }};
                          echo `/bin/date "+%Y-%m-%dT%H:%M:%S%z "` [cm-db-init] db is up | nc {{ .Values.global.ncHost }} {{ .Values.global.ncPort }};
            containers:
                - name: {{ .Chart.Name }}-init
                  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  command: ['sh', '-c']
                  args:
                      - |
                          echo `/bin/date "+%Y-%m-%dT%H:%M:%S%z "` [cm-db-init] {{.Values.global.cmHost}} job begin ... | nc {{ .Values.global.ncHost }} {{ .Values.global.ncPort }};
                          sleep 20;
                          echo `/bin/date "+%Y-%m-%dT%H:%M:%S%z "` [cm-db-init] {{.Values.global.cmHost}} job finished | nc {{ .Values.global.ncHost }} {{ .Values.global.ncPort }};
