apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    labels:
        app.kubernetes.io/name: db-secret
        helm.sh/chart: {{ include "db.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
    POSTGRES_USER: {{ "postgres" | b64enc | quote }}
    POSTGRES_DB: {{ "postgres" | b64enc | quote }}
    POSTGRES_PASSWORD: {{ randAlphaNum 12 | b64enc | quote }}

    CM_USER: {{ "cm" | b64enc | quote }}
    CM_DB: {{ "cmdb" | b64enc | quote }}
    CM_PASSWORD: {{ randAlphaNum 12 | b64enc | quote }}

    MONTE_USER: {{ "monte" | b64enc | quote }}
    MONTE_DB: {{ "montedb" | b64enc | quote }}
    MONTE_PASSWORD: {{ randAlphaNum 12 | b64enc | quote }}
