apiVersion: v1
kind: Service
metadata:
    name: {{ include "db.name" . }}
    labels:
        app.kubernetes.io/name: {{ include "db.name" . }}
        helm.sh/chart: {{ include "db.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.global.dbPort }}
            # supported values: "SCTP", "TCP", "UDP"
          protocol: TCP
    selector:
        app.kubernetes.io/name: {{ include "db.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
